price_tracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path(r'admin/', admin.site.urls),
    path(r'users/', include('users.urls')),
    path(r'', include('pt.urls'))
]

pt/urls.py
"""Defines URL patterns for pt."""

from django.urls import path
from . import views

app_name = 'pt'

urlpatterns = [
    # Home page
    path(r'', views.index, name='index'),

    # Show all entries
    path(r'entries/', views.entries, name='entries'),

    # Entry page
    path('entries/<int:entry_id>/', views.entry,
         name='entry'),

    # Page for adding a new entry
    path(r'new_entry/', views.new_entry, name='new_entry'),

    # Page for removing an entry
    path('remove_entry/<int:entry_id>/', views.remove_entry,
         name='remove_entry'),
]

users/urls.py
"""Defines url patterns for users."""

from django.urls import path
from django.contrib.auth.views import login

from . import views

app_name = 'users'
urlpatterns = [
    # Login page.
    path('login/', login, {'template_name': 'users/login.html'},
         name='login'),

    # Logout page.
    path('logout/', views.logout_view, name='logout'),

    # Registration page.
    path('register/', views.register, name='register'),
]

pt/models.py
from django.db import models
from django.contrib.auth.models import User


class Entry(models.Model):
    """A URL entry of item which price user wants to track"""
    url = models.CharField(max_length=256)
    TREND_UP = "UP"
    TREND_DOWN = "DOWN"
    TREND_CHOICES = (
        (TREND_UP, '+'),
        (TREND_DOWN, '-'),
    )
    trend = models.CharField(
        max_length=4,
        choices=TREND_CHOICES,
        null=True
    )
    owner = models.ForeignKey(User, on_delete=models.CASCADE)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model"""
        if self.trend:
            return "{}\t{}".format(self.trend, self.url)
        return "{}".format(self.url)


class Price(models.Model):
    """History of price changes"""
    entry = models.ForeignKey(Entry, on_delete=models.CASCADE)
    price = models.DecimalField(max_digits=10, decimal_places=2)
    date = models.DateTimeField(auto_now_add=False)

    class Meta:
        verbose_name_plural = 'prices'

    def __str__(self):
        """Return a string representation of the model"""
        return "{}\t{}".format(self.price, self.date)

users/models.py
from django.db import models

# Create your models here.

pt/forms.py
from django import forms
from .models import Entry


class EntryForm(forms.ModelForm):
    class Meta:
        model = Entry
        fields = ['url']
        labels = {'url': ''}

pt/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, Http404
from django.urls import reverse
from django.contrib.auth.decorators import login_required

from graphos.renderers.gchart import LineChart
from graphos.sources.model import ModelDataSource

from .models import Entry
from .models import Price
from .forms import EntryForm
import pt.fetcher as f
import pt.parser as p


def index(request):
    """The home page for Price Tracker"""
    return render(request, 'pt/index.html')


@login_required
def entries(request):
    """Show all entries"""
    entries = Entry.objects.filter(owner=request.user).order_by('id')
    context = {'entries': entries}
    return render(request, "pt/entries.html", context)


@login_required
def entry(request, entry_id):
    """Show an entry"""
    entry = get_object_or_404(Entry, id=entry_id)
    # Make sure the entry belongs to the current user.
    if entry.owner != request.user:
        raise Http404

    prices = entry.price_set.order_by('date')
    data_source = ModelDataSource(prices, fields=['date', 'price'])
    chart = LineChart(data_source)

    context = {'entry': entry, 'prices': prices, 'chart': chart}
    return render(request, "pt/entry.html", context)


@login_required
def new_entry(request):
    """Add a new entry"""
    if request.method != 'POST':
        # No data submitted; create a blank form.
        form = EntryForm()
    else:
        # POST data submitted; process data.
        form = EntryForm(request.POST)
        if form.is_valid():
            new_entry = form.save(commit=False)
            new_entry.owner = request.user
            new_entry.url = p.clip_parameters(new_entry.url)
            price, date = f.get_price_data(new_entry.url)
            if price:
                new_entry.owner = request.user
                new_entry.save()
                new_price = Price(entry=new_entry, price=price, date=date)
                new_price.save()

                return HttpResponseRedirect(reverse('pt:entries'))

    context = {'form': form}
    return render(request, 'pt/new_entry.html', context)


@login_required
def remove_entry(request, entry_id):
    """Remove an entry"""
    entry = Entry.objects.get(id=entry_id)
    if entry.owner != request.user:
        raise Http404

    if request.method != 'POST':
        # Initial request; pre-fill form with the current entry.
        form = EntryForm(instance=entry)
    else:
        # DELETE entry
        entry.delete()
        return HttpResponseRedirect(reverse('pt:entries'))

    context = {'entry': entry, 'form': form}
    return render(request, 'pt/remove_entry.html', context)

users/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect
from django.urls import reverse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm


def logout_view(request):
    """Log the user out."""
    logout(request)
    return HttpResponseRedirect(reverse('pt:index'))


def register(request):
    """Register a new user."""
    if request.method != 'POST':
        # Display blank registration form.
        form = UserCreationForm()
    else:
        # Process completed form.
        form = UserCreationForm(data=request.POST)

        if form.is_valid():
            new_user = form.save()
            # Log the user in, and then redirect to home page.
            authenticated_user = authenticate(username=new_user.username,
                                              password=request.POST['password1'])
            login(request, authenticated_user)
            return HttpResponseRedirect(reverse('pt:index'))

    context = {'form': form}
    return render(request, 'users/register.html', context)

pt/templates/pt/base.html
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Price Tracker</title>

    {% bootstrap_css %}
    {% bootstrap_javascript %}
</head>

<body>
    <!-- Static navbar -->
    <nav class="navbar navbar-default navbar-static-top">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle collapsed"
              data-toggle="collapse" data-target="#navbar"
              aria-expanded="false" aria-controls="navbar">
          </button>
          <a class="navbar-brand" href="{% url 'pt:index' %}">
              Price Tracker</a>
        </div>
        <div id="navbar" class="navbar-collapse collapse">
          <ul class="nav navbar-nav">
            {% if user.is_authenticated %}
              <li><a href="{% url 'pt:entries' %}">Entries</a></li>
            {% endif %}
          </ul>
          <ul class="nav navbar-nav navbar-right">
            {% if user.is_authenticated %}
              <li><a>Hello, {{ user.username }}.</a></li>
              <li><a href="{% url 'users:logout' %}">log out</a></li>
            {% else %}
              <li><a href="{% url 'users:register' %}">register</a></li>
              <li><a href="{% url 'users:login' %}">log in</a></li>
            {% endif %}
          </ul>
        </div><!--/.nav-collapse -->
      </div>
    </nav>
    <div class="container">
        <div class="page-header">
            {% block header %}{% endblock header %}
        </div>
        <div>
            {% block content %}{% endblock content %}
        </div>
    </div> <!-- /container -->
    </body>
</html>

pt/templates/pt/entries.html
{% extends "pt/base.html" %}

{% block header %}
  <h1>The List</h1>
{% endblock header %}

{% block content %}

  <ul>
    {% for entry in entries %}
  <li>
    {{ entry.price_set.last.price }} 
    {% if entry.trend %}
      {{ entry.trend }}
    {% endif %}
    <a href="{% url 'pt:entry' entry.id %}">{{ entry.url }}</a>
    <small>
      <a href="{% url 'pt:remove_entry' entry.id %}">remove</a>
    </small>
  </li>
    {% empty %}
      <li>No entries have been added yet.</li>
    {% endfor %}
  </ul>

  <h3><a href="{% url 'pt:new_entry' %}">Add new</h3>
{% endblock content %}

pt/templates/pt/entry.html
{% extends 'pt/base.html' %}
{% load bootstrap3 %}

{% block content %}

  <p>URL:
    <a href={{entry.url}}>{{ entry.url }}</a>
  </p>
  <p>Last price:
    {{ prices.last.price }} 
    {% if entry.trend %}
      {{ entry.trend}}
    {% endif %}
  </p>
    <ul>
    {% for price in prices reversed %}
      <li>{{ price.price }} {{ price.date }}</li>
    {% endfor %}
    </ul>
  
  <script type="text/javascript" src="https://www.google.com/jsapi"></script>
  <script type="text/javascript">
    google.load("visualization", "1", {packages:["corechart"]});
  </script>
  <p>
    {{chart.as_html}}
  </p>


{% endblock content %}

pt/templates/pt/index.html
{% extends "pt/base.html" %}

{% block header %}
  <div class='jumbotron'>
    <h1>Add URL. Price keeps tracked. That's it.</h1>
  </div>
    Supported:
    <ul>
    <li><a href='https://www.aliexpress.com'>https://www.aliexpress.com</a></li>
    </ul>
{% endblock header %}

{% block content %}
{% endblock content %}

pt/templates/pt/new_entry.html
{% extends "pt/base.html" %}
{% load bootstrap3 %}

{% block header %}
    <h2>Add a new entry:</h2>
{% endblock header %}

{% block content %}
    <form action="{% url 'pt:new_entry' %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="submit" class="btn btn-primary">add entry</button>
    {% endbuttons %}

</form>

{% endblock content %}

pt/templates/pt/remove_entry.html
{% extends "pt/base.html" %}
{% load bootstrap3 %}

{% block content %}
    <form action="{% url 'pt:remove_entry' entry.id %}" method='post' class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
        <button name="remove" class="btn btn-primary">Ok</button>
    {% endbuttons %}

</form>

{% endblock content %}

users/templates/users/login.html
{% extends "pt/base.html" %}
{% load bootstrap3 %}

{% block header %}
  <h2>Log in to your account.</h2>
{% endblock %}

{% block content %}
    
  <form method="post" action="{% url 'users:login' %}" class="form">
    {% csrf_token %}
    {% bootstrap_form form %}

    {% buttons %}
      <button name="submit" class="btn btn-primary">log in</button>
    {% endbuttons %}
    
    <input type="hidden" name="next" value="{% url 'pt:index' %}" />
  </form>
    
{% endblock content %}

users/templates/users/register.html
{% extends "pt/base.html" %}

{% block content %}

  <form method="post" action="{% url 'users:register' %}">
    {% csrf_token %}
    {{ form.as_p }}
        
    <button name="submit">register</button>
    <input type="hidden" name="next"
      value="{% url 'pt:index' %}" />
  </form>
    
{% endblock content %}